name: "Prepare composer using ./ibexa/gh-workflows/actions/prepare-composer action and execute composer install"
author: 'Ibexa AS'
description: >-
    Runs ./ibexa/gh-workflows/actions/prepare-composer action with the same input
    and then runs ramsey/composer-install action

inputs:
    gh-client-id:
        description: 'GitHub App ID'
        required: true
    gh-client-secret:
        description: 'GitHub App ID'
        required: true
    satis-network-key:
        description: 'Satis Network Key'
        required: false
    satis-network-token:
        description: 'Satis Network Token'
        required: false
    php-extensions:
        description: 'Comma-separated list of PHP extensions to install'
        required: false
        default: 'pdo_sqlite, gd'
    dependency-versions:
        description: 'Dependency version resolution strategy (lowest, highest, or locked)'
        required: false
        default: 'highest'

runs:
    using: "composite"
    steps:
        -   uses: ibexa/gh-workflows/actions/prepare-composer@extract-prepare-composer-action
            with:
                gh-client-id: ${{ inputs.gh-client-id }}
                gh-client-secret: ${{ inputs.gh-client-secret }}
                satis-network-key: ${{ inputs.satis-network-key }}
                satis-network-token: ${{ inputs.satis-network-token }}
                php-extensions: ${{ inputs.php-extensions }}

        -   uses: ramsey/composer-install@v3
            with:
                dependency-versions: ${{ inputs.dependency-versions }}
