name: "Configure ignoring known unsolvable advisories"
author: 'Ibexa AS'
description: >-
    Configures Composer `audit.ignore` list for CI tests in an allow-list way.

inputs:
    php-version:
        description: 'PHP version'
        required: true

runs:
    using: "composite"
    steps:
        -   name: Configure advisory ignore list
            shell: bash
            run: |
                script=$(mktemp)
                curl -fsSL \
                    https://raw.githubusercontent.com/ibexa/ci-scripts/main/bin/_common/configure_composer_audit_ignores.sh \
                    --output "$script"
                bash "$script" "${{ inputs.php-version }}"
