name: Post release

on:
  workflow_call:
    inputs:
      tag:
        required: true
        type: string

jobs:
  trigger-archive-maker:
    runs-on: ubuntu-latest

    steps:
      - name: Authenticate as GitHub app
        id: generate_token
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        with:
          client-id: ${{ secrets.AUTOMATION_CLIENT_ID }}
          private-key: ${{ secrets.AUTOMATION_CLIENT_SECRET }}
          owner: ibexa

      - name: Extract tag name
        id: tag
        run: |
          TAG="${{ inputs.tag }}"
          VERSION="${TAG#v}"
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Trigger archive-maker via repository_dispatch
        uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9.0.0
        with:
          github-token: ${{ steps.generate_token.outputs.token }}
          script: |
            await github.rest.repos.createDispatchEvent({
              owner: 'ibexa',
              repo: 'archive-maker',
              event_type: 'ibexa-product-release',
              client_payload: {
                product: '${{ github.event.repository.name }}',
                version: '${{ steps.tag.outputs.version }}',
                skeleton_version: '${{ steps.tag.outputs.version }}',
                php_version: '8.3',
              }
            })
