name: PR check
on:
  workflow_call: ~

jobs:
  test-base-branch:
    name: Pull Request base branch verification
    runs-on: ubuntu-latest
    steps:
      - name: Get PR's composer.json
        id: pr
        shell: bash
        run: |
          response=$(gh api --method GET "/repos/${REPOSITORY}/contents/composer.json" -f ref="$BRANCH")
          {
            echo 'data<<EOF'
            echo "$response"
            echo EOF
          } >> "$GITHUB_OUTPUT"
        env:
          BRANCH: ${{ github.event.pull_request.head.ref }}
          GITHUB_TOKEN: ${{ github.token }}
          REPOSITORY: ${{ github.event.pull_request.head.repo.full_name }}
      - name: Get base's composer.json
        id: base
        shell: bash
        run: |
          response=$(gh api --method GET "/repos/${REPOSITORY}/contents/composer.json" -f ref="$BRANCH")
          {
            echo 'data<<EOF'
            echo "$response"
            echo EOF
          } >> "$GITHUB_OUTPUT"
        env:
          BRANCH: ${{ github.event.pull_request.base.ref }}
          GITHUB_TOKEN: ${{ github.token }}
          REPOSITORY: ${{ github.event.pull_request.base.repo.full_name }}
      - name: Verify base branch
        run: |
          PR_BRANCH_ALIAS=$(echo $PR_DATA | jq -r '.["content"]' | base64 --decode | jq -r '.["extra"]["branch-alias"] | flatten | .[0]')
          BASE_BRANCH_ALIAS=$(echo $BASE_DATA | jq -r '.["content"]' | base64 --decode | jq -r '.["extra"]["branch-alias"] | flatten | .[0]')
          if [ "$PR_BRANCH_ALIAS" != "$BASE_BRANCH_ALIAS" ]; then 
            echo "Base branch has different branch-alias than PR."
            echo "Pull Request: $PR_BRANCH_ALIAS"
            echo "Base branch: $BASE_BRANCH_ALIAS"
            exit 1; 
          fi
        env:
          PR_DATA: ${{ steps.pr.outputs.data }}
          BASE_DATA: ${{ steps.base.outputs.data }}
