name: PR Checks

on:
  workflow_call: ~

jobs:
  check-up-to-date:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Check if branch is up to date with base branch
        env:
          BASE_BRANCH: ${{ github.event.pull_request.base.ref }}
        run: |
          set -e
          echo "Base branch: $BASE_BRANCH"
          echo "PR branch: $GITHUB_HEAD_REF"
          git fetch origin "$BASE_BRANCH"
          git fetch origin "$GITHUB_HEAD_REF"
          BASE_BRANCH_HEAD=$(git rev-parse "origin/$BASE_BRANCH")
          MERGE_BASE=$(git merge-base HEAD "origin/$BASE_BRANCH")
          echo "BASE_BRANCH_HEAD: $BASE_BRANCH_HEAD"
          echo "MERGE_BASE: $MERGE_BASE"
          if [ "$MERGE_BASE" = "$BASE_BRANCH_HEAD" ]; then
            echo "Branch is up to date with $BASE_BRANCH."
          else
            echo "Branch is NOT up to date with $BASE_BRANCH. Please rebase or merge $BASE_BRANCH." >&2
            exit 1
          fi
  detect-languages:
    runs-on: ubuntu-latest
    outputs:
      languages: ${{ steps.list.outputs.languages }}
    steps:
      - name: List repository languages
        id: list
        uses: austenstone/list-repository-languages@main
  # Conditional builds
  build-dotnet:
    needs: [detect-languages]
    continue-on-error: true
    if: contains(needs.detect-languages.outputs.languages, '"C#"')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Build & Test
        run: |
          dotnet restore
          dotnet build --no-restore
          dotnet test  --no-restore --verbosity normal
  build-scala:
    needs: [detect-languages]
    if: contains(needs.detect-languages.outputs.languages, '"Scala"')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java (for sbt)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 11

      - name: Build & Test
        run: |
          sbt clean compile test
  build-frontend:
    needs: [detect-languages]
    if: |
      contains(needs.detect-languages.outputs.languages, '"JavaScript"') ||
      contains(needs.detect-languages.outputs.languages, '"TypeScript"') ||
      contains(needs.detect-languages.outputs.languages, '"Vue"')
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20, 18]
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install, Lint & Test
        run: |
          npm ci
          npm run lint
          npm test
