name: Repository Reactor / Linters

on:
  workflow_call:

jobs:
  yamljson:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: json-yaml-validate
        uses: GrantBirki/json-yaml-validate@3ff75979f3b21171f2e8a44705f0ff4bed30bbc0 # v5.0.0
        with:
          use_dot_match: "false"
