name: Rector PHP

on:
    workflow_call:
        secrets:
            SATIS_NETWORK_KEY:
                required: false
            SATIS_NETWORK_TOKEN:
                required: false
            TRAVIS_GITHUB_TOKEN:
                required: false
jobs:
    rector:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Setup PHP Action
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}

            - if: env.SATIS_NETWORK_KEY != ''
              name: 'Add composer keys for private packagist'
              run: |
                  composer config http-basic.updates.ibexa.co $SATIS_NETWORK_KEY $SATIS_NETWORK_TOKEN
                  composer config github-oauth.github.com $TRAVIS_GITHUB_TOKEN
              env:
                  SATIS_NETWORK_KEY: ${{ secrets.SATIS_NETWORK_KEY }}
                  SATIS_NETWORK_TOKEN: ${{ secrets.SATIS_NETWORK_TOKEN }}
                  TRAVIS_GITHUB_TOKEN: ${{ secrets.TRAVIS_GITHUB_TOKEN }}

            - name: 'Add Ibexa Rector dependency'
              run: |
                  # determine product version, fall back to ~5.0.x-dev if not possible  
                  version='~'$(jq -r '.extra | ."branch-alias" | ."dev-main" // ."dev-master" // "5.0.x-dev"' < composer.json)
                  composer require --dev --no-update ibexa/rector:"$version"

            - name: 'Install Composer dependencies'
              uses: ramsey/composer-install@v3
              with:
                  dependency-versions: highest

            - name: 'Run rector'
              run: vendor/bin/rector process --dry-run --ansi
