name: Rector PHP

on:
    workflow_call:
        secrets:
            SATIS_NETWORK_KEY:
                required: false
            SATIS_NETWORK_TOKEN:
                required: false
            AUTOMATION_CLIENT_ID:
                required: false
            AUTOMATION_CLIENT_SECRET:
                required: false
jobs:
    rector:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v6

            - uses: ibexa/gh-workflows/actions/composer-install@main
              with:
                  gh-client-id: ${{ secrets.AUTOMATION_CLIENT_ID }}
                  gh-client-secret: ${{ secrets.AUTOMATION_CLIENT_SECRET }}
                  satis-network-key: ${{ secrets.SATIS_NETWORK_KEY }}
                  satis-network-token: ${{ secrets.SATIS_NETWORK_TOKEN }}

            - name: 'Run rector'
              run: vendor/bin/rector process --dry-run --ansi
