name: Ibexa Reusable / Repository Reactor

on:
  workflow_call:
    inputs:
      feature_linter:
        default: true
        type: boolean

jobs:
  linters:
    if: ${{ inputs.feature_linter }}
    uses: ibexa/gh-workflows/.github/workflows/reactor-linters.yml@main
    secrets: inherit