name: Upload Test Artifacts

on:
    workflow_run:
        workflows: ["Browser tests"]
        types:
            - completed

jobs:
    upload-test-artifacts:
        runs-on: ubuntu-latest
        if: ${{ github.event.workflow_run.conclusion == 'failure' }}
        steps:
            - name: Download artifact
              uses: dawidd6/action-download-artifact@v3
              with:
                  workflow: browser-tests.yaml
                  run_id: ${{ github.event.workflow_run.id }}
                  path: artifacts

            - name: Upload screenshots from failed tests
              uses: actions/upload-artifact@v4
              with:
                  name: failed-test-screenshots
                  path: artifacts/**/build/project/behat-output/*.png
                  if-no-files-found: ignore
                  retention-days: 14
