name: Upmerge branch (callee)

on:
  workflow_call:
    secrets:
      AUTOMATION_CLIENT_ID:
        description: 'GitHub App ID'
        required: true
      AUTOMATION_CLIENT_SECRET:
        description: 'GitHub App private key'
        required: true

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub App Token
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        id: generate_token
        with:
          client-id: ${{ secrets.AUTOMATION_CLIENT_ID }}
          private-key: ${{ secrets.AUTOMATION_CLIENT_SECRET }}
          owner: ${{ github.repository_owner }}

      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0
          token: ${{ steps.generate_token.outputs.token }}

      - name: Set environment
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com>"

      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@e6f261660910b273384c5c42b17a0217881b217a # v5.6.0

      - name: Get merge map
        id: map
        # Allow failures to be ignored.
        # We will consider output as empty
        continue-on-error: true
        shell: bash
        run: |
          response=$(gh api /repos/ibexa/upmerge-map/contents/${{ github.repository }})
          {
            echo 'data<<EOF'
            echo "$response"
            echo EOF
          } >> "$GITHUB_OUTPUT"
        env:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}

      # Parse json and find destination branch and repository
      - name: Set variables
        id: destinations
        if: ${{ steps.map.outputs.data }}
        run: |
          cat > input.json <<'EOF'
          ${{ steps.map.outputs.data }}
          EOF
          jq -r '.["content"]' input.json | base64 --decode | jq -c . > map.json
          branch=${{ env.GITHUB_REF_SLUG }}
          echo Looking for destination for branch $branch
          destination=$(jq -r '.["${{ env.GITHUB_REF_SLUG }}"] | select (.!=null)' map.json)
          echo Destination branch found. It is ${destination} branch
          echo "SOURCE_BRANCH=$branch" >> $GITHUB_ENV
          echo "DEST_BRANCH=$destination" >> $GITHUB_ENV
          echo "destination=$destination" >> $GITHUB_OUTPUT

      - name: Checkout code
        if: ${{ steps.destinations.outputs.destination }}
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          ref: ${{ env.DEST_BRANCH }}
          fetch-depth: 0
          token: ${{ steps.generate_token.outputs.token }}

      - name: Perform Upmerge of ${{ env.SOURCE_BRANCH }} to ${{ env.DEST_BRANCH }}
        if: ${{ steps.destinations.outputs.destination }}
        run: |
          git merge -m "Merged branch '${{ env.SOURCE_BRANCH }}' into ${{ env.DEST_BRANCH }}" origin/$SOURCE_BRANCH

      - name: Push changes
        if: ${{ steps.destinations.outputs.destination }}
        run: |
          git push origin "HEAD:${DEST_BRANCH}"
